# Generated by Django 3.0.8 on 2021-12-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_buyer',
            field=models.BooleanField(default=False, verbose_name='....'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_supplier',
            field=models.BooleanField(default=False, verbose_name='is staff'),
        ),
    ]
