# Generated by Django 3.0.8 on 2021-12-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200722_0405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'Pregnant Women'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'PWD'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'Elder'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Out of School Youth'},
        ),
        migrations.AlterField(
            model_name='product',
            name='sortno',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterModelTable(
            name='buyer',
            table='store_buyer',
        ),
        migrations.AlterModelTable(
            name='product',
            table='store_product',
        ),
        migrations.AlterModelTable(
            name='season',
            table='store_season',
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='store_supplier',
        ),
    ]
