# Generated by Django 3.0.8 on 2021-12-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211205_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='user',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.CharField(max_length=220, verbose_name='Barangay'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sortno',
            field=models.CharField(max_length=120, unique=True, verbose_name='Barangay'),
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.CharField(max_length=220, verbose_name='Barangay'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=220, verbose_name='Barangay'),
        ),
    ]
